local-simulation:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com

mutiny:
  cre-cli:
    don-family: "zone-a"
  account:
    workflow-owner-address: "0x8b9eDA4BC340cD9daF11641C8162ec28f155D837"
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com
    - chain-name: ethereum-mainnet
      url: https://ethereum-rpc.publicnode.com

testnet4:
  cre-cli:
    don-family: "zone-a"
  account:
    workflow-owner-address: "0x8b9eDA4BC340cD9daF11641C8162ec28f155D837"
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com
    - chain-name: ethereum-mainnet
      url: https://ethereum-rpc.publicnode.com

alpha-mainnet:
  cre-cli:
    don-family: "zone-a"
  account:
    workflow-owner-address: "0x8b9eDA4BC340cD9daF11641C8162ec28f155D837"
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com
    - chain-name: ethereum-mainnet
      url: https://ethereum-rpc.publicnode.com
