# ==========================================================================
# CRE PROJECT SETTINGS FILE
# ==========================================================================
# Project-specific settings for CRE CLI targets.
# Each target defines cre-cli, account, and rpcs groups.
#
# Example custom target:
# my-target:
#   cre-cli:
#     don-family: "zone-a"                          # Required: Workflow DON Family
#   account:
#     workflow-owner-address: "0x123..."            # Optional: Owner wallet/MSIG address (used for --unsigned transactions)
#   rpcs:
#     - chain-name: ethereum-mainnet                # Required: Chain RPC endpoints
#       url: "https://mainnet.infura.io/v3/KEY"

# ==========================================================================
local-simulation:
  # Using public RPC endpoint (no authentication required)
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com

# ==========================================================================
staging:
  cre-cli:
    don-family: "zone-a"
  account:
    workflow-owner-address: "0x531c76d8c5ed926d0d735605481289393fb41397"
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com

# ==========================================================================
production-testnet:
  cre-cli:
    don-family: "zone-a"
  account:
    workflow-owner-address: "0x531c76d8c5ed926d0d735605481289393fb41397"
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com
    - chain-name: ethereum-mainnet
      url: https://ethereum-rpc.publicnode.com
